# Generated by Django 5.0.4 on 2024-06-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_invoice_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('recency', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('monetary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('clusters', models.IntegerField()),
                ('group', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
