# Generated by Django 5.0.4 on 2024-08-02 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_datasetupload_file_datasetupload_dataset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatasetUpload',
        ),
    ]
