# Generated by Django 5.0.4 on 2024-12-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_delete_datasetupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFileName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default=None, max_length=255)),
            ],
        ),
    ]
